name: MongoDB.MongoDBCLI PR
# based off of https://github.com/nushell/nushell/blob/main/.github/workflows/winget-submission.yml

on:
    workflow_dispatch:
    schedule:
        - cron: 3 0/4 * * *
env:
    PackageName: MongoDB.MongoDBCLI
    WebsiteURL: https://www.mongodb.com/try/download/tools
    PackageFilter: mongocli

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Utesgui
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update package
        id: get_version
        working-directory: Utesgui
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
          WINGET_PKGS_FORK_REPO: ${{ vars.WINGET_PKGS_FORK_REPO }}
        run: .\scripts\Update-${{ env.PackageName }}.ps1


