name: Run Get-MSIFileInformation

on:
  workflow_dispatch:
    inputs:
      websiteURL:
        description: 'Website URL'
        required: true

jobs:
  run-msi-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    #   - name: Set up PowerShell
    #     uses: actions/setup-powershell@v2

      - name: Run Get-MSIFileInformation
        run: |
          $WebsiteURL = '${{ github.event.inputs.websiteURL }}'
          Import-Module .\modules\WingetMaintainerModule\Public\Get-MSIFileInformation.ps1
          Get-MSIFileInformation -WebsiteURL $WebsiteURL
        shell: pwsh

    #   - name: Output result
    #     run: |
    #       Write-Output "MSI File Information:"
    #       Get-Content -Path .\output.txt
    #     shell: pwsh