name: GH Release based Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 0/4 * * *' # every 4 hours

jobs:
  update-releasebased:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: "Yubico.Authenticator"
            repo: "Yubico/yubioath-flutter"
            url: "https://github.com/Yubico/yubioath-flutter/releases/download/{VERSION}/yubico-authenticator-{VERSION}-win64.msi"
#          - id: "Yubico.YubikeyManager"
#            repo: "Yubico/yubikey-manager-qt"
#            url: "https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-{VERSION}-win32.exe"
          - id: "Yubico.YubiKeyManagerCLI"
            repo: "Yubico/yubikey-manager"
            url: "https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-{VERSION}-win64.msi"
          - id: "Anki.Anki"
            repo: "ankitects/anki"
            url: "https://github.com/ankitects/anki/releases/download/{VERSION}/anki-{VERSION}-windows-qt6.exe"
          - id: "EdgeTX.Companion"
            repo: "EdgeTX/edgetx"
            url: "https://github.com/EdgeTX/edgetx/releases/download/{VERSION}/edgetx-cpn-win64-{VERSION}.zip"
          - id: "Betaflight.Betaflight-Configurator"
            repo: "betaflight/betaflight-configurator"
            url: "https://github.com/betaflight/betaflight-configurator/releases/download/{VERSION}/betaflight-configurator_{VERSION}_win64-installer.exe"
            
    steps:
    - name: Update Packages
      uses: michidk/winget-updater@v1
      with:
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}
        komac-token: ${{ secrets.WINGET_PAT }}
        custom-fork-owner: damn-good-b0t
