name: GH Release based Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 0/4 * * *' # every 4 hours

jobs:
  update:
    name: Update package ${{ matrix.id }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - id: "Yubico.Authenticator"
            repo: "Yubico/yubioath-flutter"
            url: "https://github.com/Yubico/yubioath-flutter/releases/download/{VERSION}/yubico-authenticator-{VERSION}-win64.msi"
          - id: "Yubico.YubikeyManager"
            repo: "Yubico/yubikey-manager-qt"
            url: "https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-{VERSION}-win32.exe"
          - id: "Yubico.YubikeyManagerCLI"
            repo: "Yubico/yubikey-manager"
            url: "https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-{VERSION}-win64.msi"
    steps:
    - name: Update Packages
      uses: michidk/winget-updater@v1
      with:
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}
        komac-token: ${{ secrets.WINGET_PAT }}
        custom-fork-owner: damn-good-b0t

  cleanup:
    name: Cleanup branches
    needs: update # Not necessarily needed as PRs don't get closed that quick but still nice to have it in order
    runs-on: ubuntu-latest

    steps:
    - name: Run Komac
      uses: michidk/run-komac@v2
      with:
        args: 'cleanup --token=${{ secrets.WINGET_PAT }}'
        custom-fork-owner: damn-good-b0t