name: GH Release based Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *' # Scheduled to run daily at 03:00

jobs:
  update:
    name: Update package ${{ matrix.id }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - id: "Yubico.Authenticator"
            repo: "Yubico/yubioath-flutter"
            url: "https://github.com/Yubico/yubioath-flutter/releases/download/{VERSION}/yubico-authenticator-{VERSION}-win64.msi"
#          - id: "Casey.Just"
#            repo: "casey/just"
#            url: "https://github.com/casey/just/releases/download/{VERSION}/just-{VERSION}-x86_64-pc-windows-msvc.zip"
    steps:
    - name: Update Packages
      uses: michidk/winget-updater@v1
      with:
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}
        komac-token: ${{ secrets.WINGET_PAT }}
        custom-fork-owner: damn-good-b0t

  cleanup:
    name: Cleanup branches
    needs: update # Not necessarily needed as PRs don't get closed that quick but still nice to have it in order
    runs-on: ubuntu-latest

    steps:
    - name: Run Komac
      uses: michidk/run-komac@v2
      with:
        args: 'branch cleanup --token=${{ secrets.WINGET_PAT }}'