name: GH Release based Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 0/4 * * *' # every 4 hours

jobs:
  update-releasebased:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Test' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: "Yubico.Authenticator"
            repo: "Yubico/yubioath-flutter"
            url: "https://github.com/Yubico/yubioath-flutter/releases/download/{VERSION}/yubico-authenticator-{VERSION}-win64.msi"
#          - id: "Yubico.YubikeyManager"
#            repo: "Yubico/yubikey-manager-qt"
#            url: "https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-{VERSION}-win32.exe"
          - id: "Yubico.YubiKeyManagerCLI"
            repo: "Yubico/yubikey-manager"
            url: "https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-{VERSION}-win64.msi"
          - id: "Anki.Anki"
            repo: "ankitects/anki"
            url: "https://github.com/ankitects/anki/releases/download/{VERSION}/anki-{VERSION}-windows-qt6.exe"
          - id: "EdgeTX.Companion"
            repo: "EdgeTX/edgetx"
            url: "https://github.com/EdgeTX/edgetx/releases/download/v{VERSION}/edgetx-cpn-win64-v{VERSION}.zip"
          - id: "Betaflight.Betaflight-Configurator"
            repo: "betaflight/betaflight-configurator"
            url: "https://github.com/betaflight/betaflight-configurator/releases/download/{VERSION}/betaflight-configurator_{VERSION}_win64-installer.exe"
          - id: "h3poteto.fedistar"
            repo: "h3poteto/fedistar"
            url: "https://github.com/h3poteto/fedistar/releases/download/v{VERSION}/fedistar_{VERSION}_x64_en-US.msi"
          - id: "hoppscotch.Hoppscotch"
            repo: "hoppscotch/releases"
            url: "https://github.com/hoppscotch/releases/releases/download/v{VERSION}/Hoppscotch_win_x64.msi"
          - id: "AdGuard.dnsproxy"
            repo: "AdguardTeam/dnsproxy"
            url: "https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-386-v{VERSION}.zip https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-amd64-v{VERSION}.zip https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-arm64-v{VERSION}.zip"
          - id: "OpenTofu.Tofu"
            repo: "opentofu/opentofu"
            url: "https://github.com/opentofu/opentofu/releases/download/v{VERSION}/tofu_{VERSION}_windows_386.zip https://github.com/opentofu/opentofu/releases/download/v{VERSION}/tofu_{VERSION}_windows_amd64.zip"
          - id: "mitmproxy.mitmproxy"
            repo: "mitmproxy/mitmproxy"
            url: "https://downloads.mitmproxy.org/{VERSION}/mitmproxy-{VERSION}-windows-x86_64-installer.exe"
          - id: "commercialhaskell.stack"
            repo: "commercialhaskell/stack"
            url: "https://github.com/commercialhaskell/stack/releases/download/v{VERSION}/stack-{VERSION}-windows-x86_64-installer.exe"
          - id: "JohnMacFarlane.Pandoc"
            repo: "jgm/pandoc"
            url: "https://github.com/jgm/pandoc/releases/download/{VERSION}/pandoc-{VERSION}-windows-x86_64.msi"
          - id: "Neovim.Neovim"
            repo: "neovim/neovim"
            url: "https://github.com/neovim/neovim/releases/download/v{VERSION}/nvim-win64.msi"
#          - id: "RustDesk.RustDesk"
#            repo: "rustdesk/rustdesk"
#            url: "https://github.com/rustdesk/rustdesk/releases/download/{VERSION}/rustdesk-{VERSION}-x86-sciter.exe https://github.com/rustdesk/rustdesk/releases/download/{VERSION}/rustdesk-{VERSION}-x86_64.exe"
          - id: "AquaSecurity.Trivy"
            repo: "aquasecurity/trivy"
            url: "https://github.com/aquasecurity/trivy/releases/download/v{VERSION}/trivy_{VERSION}_windows-64bit.zip"
          - id: "TeXstudio.TeXstudio"
            repo: "texstudio-org/texstudio"
            url: " https://github.com/texstudio-org/texstudio/releases/download/{VERSION}/texstudio-{VERSION}-win-qt6.exe"
          - id: "Levminer.Authme"
            repo: "Levminer/authme"
            url: "https://github.com/Levminer/authme/releases/download/{VERSION}/authme-{VERSION}-windows-x64.msi"
          - id: "StephanDilly.gitui"
            repo: "extrawurst/gitui"
            url: "https://github.com/extrawurst/gitui/releases/download/v{VERSION}/gitui-win.msi" 
          - id: "ameshkov.dnslookup"
            repo: "ameshkov/dnslookup"
            url: "https://github.com/ameshkov/dnslookup/releases/download/v{VERSION}/dnslookup-windows-386-v{VERSION}.zip https://github.com/ameshkov/dnslookup/releases/download/v{VERSION}/dnslookup-windows-amd64-v{VERSION}.zip" 
          - id: "CrowdSecurity.CrowdSec"
            repo: "crowdsecurity/crowdsec"
            url: "https://github.com/crowdsecurity/crowdsec/releases/download/v{VERSION}/crowdsec_{VERSION}.msi" 
          - id: "JanProchazka.dbgate"
            repo: "dbgate/dbgate"
            url: "https://github.com/dbgate/dbgate/releases/download/v{VERSION}/dbgate-{VERSION}-win_arm64.exe https://github.com/dbgate/dbgate/releases/download/v{VERSION}/dbgate-{VERSION}-win_x64.exe https://github.com/dbgate/dbgate/releases/download/v{VERSION}/dbgate-{VERSION}-win.exe"      
          - id: "terreng.SimpleWebServer"
            repo: "terreng/simple-web-server"
            url: "https://github.com/terreng/simple-web-server/releases/download/v{VERSION}/Simple-Web-Server-Installer-{VERSION}-x64.exe https://github.com/terreng/simple-web-server/releases/download/v{VERSION}/Simple-Web-Server-Installer-{VERSION}-ia32.exe https://github.com/terreng/simple-web-server/releases/download/v{VERSION}/Simple-Web-Server-Installer-{VERSION}-arm64.exe"
          - id: "jendrikseipp.RedNotebook"
            repo: "jendrikseipp/rednotebook"
            url: "https://github.com/jendrikseipp/rednotebook/releases/download/v{VERSION}/rednotebook-{VERSION}.exe"          
          - id: "f4exb.sdrangel"
            repo: "f4exb/sdrangel"
            url: "https://github.com/f4exb/sdrangel/releases/download/v{VERSION}/sdrangel-{VERSION}-win64.exe"
          - id: "Fabio286.antares"
            repo: "antares-sql/antares"
            url: "https://github.com/antares-sql/antares/releases/download/v{VERSION}/Antares-{VERSION}-win_x64.exe"       
#          - id: "svenstaro.miniserve"
#            repo: "svenstaro/miniserve"
#            url: "https://github.com/svenstaro/miniserve/releases/download/v{VERSION}/miniserve-{VERSION}-x86_64-pc-windows-msvc.exe"
          - id: "altair-graphql.altair"
            repo: "altair-graphql/altair"
            url: "https://github.com/altair-graphql/altair/releases/download/v{VERSION}/altair_{VERSION}_x64_win.exe"  
#          - id: "ViGEm.HidHide"
#            repo: "nefarius/HidHide"
#            url: "https://github.com/nefarius/HidHide/releases/download/v{VERSION}/HidHide_{VERSION}_x64.exe"
          - id: "LibreHardwareMonitor.LibreHardwareMonitor"
            repo: "LibreHardwareMonitor/LibreHardwareMonitor"
            url: "https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v{VERSION}/LibreHardwareMonitor-net472.zip"  
  
    
    steps:
    - name: Update Packages
      uses: b0t-at/winget-updater@b0t-main
      with:
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}
        komac-token: ${{ secrets.WINGET_PAT }}
        #komac-version: nightly
        komac-version: 2.2.1
        custom-fork-owner: damn-good-b0t
        submit: ${{ vars.SUBMIT_PR }}
