name: Cleanup Branches
on:
  workflow_dispatch:
  schedule:
    - cron:  '3 12 * * *'

jobs:
  komac-cleanup:
       name: komac new and submit
       if:  false == ${{ inputs.submit }} 
       runs-on: ubuntu-latest
   
       steps:
       - name: Run Komac
         uses: michidk/run-komac@v2
         with:
            args: 'cleanup --token=${{ secrets.WINGET_PAT }}'
            custom-fork-owner: damn-good-b0t