name: Update Package
on:
  workflow_dispatch:
    inputs:
      identifier:
        description: Package.Identifier
        required: true
      urls:
        description: URLs space separated
        required: false
      version:
        description: Version
        required: false
      WebsiteURL:
        description: WebsiteURL
        required: false
      submit:
        description: 'True to auto-submit'
        required: true
        type: boolean
        default: false
      resolves: 
        description: 'resolves this issues'
        required: false
      With:
        required: true
        type: choice
        description: 'WinGetCreate or komac'
        default: 'komac'
        options:
        - komac
        - WinGetCreate
#  schedule:
#    - cron:  '3 12 * * *' # every 4 hours

permissions: 
  contents: write
  pull-requests: write

jobs:
  komac-update:
    name: ${{ inputs.identifier }} -s ${{ inputs.submit }} 
#    if:  ${{ inputs.submit }} 
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update package
        id: update_version
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
          WINGET_PKGS_FORK_REPO: ${{ vars.WINGET_PKGS_FORK_REPO }}
          PackageName: ${{ inputs.identifier }}
          With: ${{ inputs.With }}
          Submit: ${{ inputs.submit }}
          latestVersion: ${{ inputs.version }}
          latestVersionUrl: ${{ inputs.urls }}
          resolves: ${{ inputs.resolves }}
          WebsiteURL: ${{ inputs.WebsiteURL }}
        run: .\scripts\generic.ps1
      # - name: Create Pull Request
      #   if: ${{ inputs.submit == true }}
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: Update manifests for ${{ matrix.PackageName }}
      #     branch: manifest-update-${{ matrix.PackageName }}
      #     add-paths: 'manifests'
      #     delete-branch: true
      #     title: '[Manifest] Update ${{ matrix.PackageName }}'
      #     body: |
      #       Update manifest of ${{ matrix.PackageName }}
      #     labels: |
      #       automated pr