name: Test Manifest

on:
  workflow_dispatch:

jobs:
  test:
    name: Test manifest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Sandbox Script
        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/microsoft/winget-pkgs/master/Tools/SandboxTest.ps1 -OutFile SandboxTest.ps1
      - name: Run Sandbox Script
        run: .\SandboxTest.ps1 -WinGetVersion 1.7 -Script {winget install Git.Git --accept-source-agreements}
