name: Test-Screenshot

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  screenshot:
    runs-on: windows-latest  # Using a GitHub-hosted Windows runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%dT%H_%M_%S')" >> $env:GITHUB_ENV

      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install FFmpeg
        run: |
          winget install BtbN.FFmpeg.GPL --accept-source-agreements --accept-package-agreements --verbose-logs 
      - name: Take screenshot using FFmpeg
        shell: powershell
        run: |
          # Create directory for downloads
          New-Item -ItemType Directory -Path ".\downloads" -Force
 
          # Use FFmpeg to capture screen
          Write-Host "Capturing screenshot with FFmpeg..."
          ffmpeg -f gdigrab -framerate 1 -i desktop -frames:v 1 screenshot.png
          
          # Verify screenshot was created
          if (Test-Path "./screenshots/screenshot.png") {
            Write-Host "Screenshot captured successfully"
          } else {
            Write-Error "Screenshot capture failed"
            exit 1
          }

          mv .\screenshot.png .\screenshots\screenshot-${{ env.date }}.png

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "${{ github.action }} - new screenhsot"
            file_pattern: ./screenshots/screenshot-${{ env.date }}.png

    #   - name: Upload Screenshot Artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: virtual-display-screenshots
    #       path: screenshot.png
    #       retention-days: 5  # Artifacts will be kept for 5 days