name: Test-Screenshot

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  screenshot:
    runs-on: windows-latest  # Using a GitHub-hosted Windows runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%dT%H_%M_%S')}" >> $GITHUB_ENV
      - name: Take screenshot using FFmpeg
        shell: powershell
        run: |
          # Create directory for downloads
          New-Item -ItemType Directory -Path ".\downloads" -Force

          winget install BtbN.FFmpeg.GPL --accept-package-agreements --verbose-logs
                    
          # Use FFmpeg to capture screen
          Write-Host "Capturing screenshot with FFmpeg..."
          & ffmpeg -f gdigrab -framerate 1 -i desktop -frames:v 1 screenshot-${{ env.date }}.png
          mv .\screenshot-${{ env.date }}.png .\screenshots\screenshot-${{ env.date }}.png
          
          # Verify screenshot was created
          if (Test-Path "./screenshots/screenshot-${{ env.date }}.png") {
            Write-Host "Screenshot captured successfully"
          } else {
            Write-Error "Screenshot capture failed"
            exit 1
          }

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "${{ github.action }} - new screenhsot"
            file_pattern: ./screenshots/screenshot-${{ env.date }}.png

    #   - name: Upload Screenshot Artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: virtual-display-screenshots
    #       path: screenshot.png
    #       retention-days: 5  # Artifacts will be kept for 5 days