name: GH Package Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '3 0/4 * * *' # every 4 hours
  push:
    branches:
      - main
    paths:
      - .github/workflows/github-releases.yml

jobs:
  update-releasebased:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Test' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: activescott.lessmsi
            repo: activescott/lessmsi
            url: https://github.com/activescott/lessmsi/releases/download/v{VERSION}/lessmsi-v{VERSION}.zip
          - id: ActivityWatch.ActivityWatch
            repo: ActivityWatch/activitywatch
            url: https://github.com/ActivityWatch/activitywatch/releases/download/v{VERSION}/activitywatch-v{VERSION}-windows-x86_64-setup.exe
          - id: AdGuard.AdGuardHome
            repo: AdguardTeam/AdGuardHome
            url: https://github.com/AdguardTeam/AdGuardHome/releases/download/v{VERSION}/AdGuardHome_windows_386.zip https://github.com/AdguardTeam/AdGuardHome/releases/download/v{VERSION}/AdGuardHome_windows_amd64.zip https://github.com/AdguardTeam/AdGuardHome/releases/download/v{VERSION}/AdGuardHome_windows_arm64.zip
          - id: AdGuard.dnsproxy
            repo: AdguardTeam/dnsproxy
            url: https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-386-v{VERSION}.zip https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-amd64-v{VERSION}.zip https://github.com/AdguardTeam/dnsproxy/releases/download/v{VERSION}/dnsproxy-windows-arm64-v{VERSION}.zip
          - id: AlbrechtL.WelloIO
            repo: AlbrechtL/welle.io
            url: https://github.com/AlbrechtL/welle.io/releases/download/v{VERSION}/welle.io-{VERSION}-Windows-setup_x86_64.exe
          - id: AllanBoll.FilesRemote
            repo: allanrbo/filesremote
            url: https://github.com/allanrbo/filesremote/releases/download/v{VERSION}/filesremote-{VERSION}-Windows-x86_64-static.zip
          - id: altair-graphql.altair
            repo: altair-graphql/altair
            url: https://github.com/altair-graphql/altair/releases/download/v{VERSION}/altair_{VERSION}_x64_win.exe
          - id: ameshkov.dnslookup
            repo: ameshkov/dnslookup
            url: https://github.com/ameshkov/dnslookup/releases/download/v{VERSION}/dnslookup-windows-386-v{VERSION}.zip https://github.com/ameshkov/dnslookup/releases/download/v{VERSION}/dnslookup-windows-amd64-v{VERSION}.zip
          - id: Anki.Anki
            repo: ankitects/anki
            url: https://github.com/ankitects/anki/releases/download/{VERSION}/anki-{VERSION}-windows-qt6.exe
          - id: AppFlowy.AppFlowy
            repo: AppFlowy-IO/AppFlowy
            url: https://github.com/AppFlowy-IO/AppFlowy/releases/download/{VERSION}/AppFlowy-{VERSION}-windows-x86_64.exe
          - id: AquaSecurity.Trivy
            repo: aquasecurity/trivy
            url: https://github.com/aquasecurity/trivy/releases/download/v{VERSION}/trivy_{VERSION}_windows-64bit.zip
          - id: argoproj.argocd
            repo: argoproj/argo-cd
            url: https://github.com/argoproj/argo-cd/releases/download/v{VERSION}/argocd-windows-amd64.exe
          - id: Betaflight.Betaflight-Configurator
            repo: betaflight/betaflight-configurator
            url: https://github.com/betaflight/betaflight-configurator/releases/download/{VERSION}/betaflight-configurator_{VERSION}_win64-installer.exe
          - id: CargoLambda.CargoLambda
            repo: cargo-lambda/cargo-lambda
            url: https://github.com/cargo-lambda/cargo-lambda/releases/download/v{VERSION}/cargo-lambda-v{VERSION}.windows-x64.zip
          - id: commercialhaskell.stack
            repo: commercialhaskell/stack
            url: https://github.com/commercialhaskell/stack/releases/download/v{VERSION}/stack-{VERSION}-windows-x86_64-installer.exe
          - id: divVerent.AAAAXY
            repo: divVerent/aaaaxy
            url: https://github.com/divVerent/aaaaxy/releases/download/v{VERSION}/aaaaxy-windows-amd64-v{VERSION}.zip https://github.com/divVerent/aaaaxy/releases/download/v{VERSION}/aaaaxy-windows-amd64-v{VERSION}.zip
          - id: Docker.DockerCompose
            repo: docker/compose
            url: https://github.com/docker/compose/releases/download/v{VERSION}/docker-compose-windows-x86_64.exe https://github.com/docker/compose/releases/download/v{VERSION}/docker-compose-windows-aarch64.exe
          - id: Dystroy.broot
            repo: Canop/broot
            url: https://github.com/Canop/broot/releases/download/v{VERSION}/broot_{VERSION}.zip
          - id: EdgeTX.Companion
            repo: EdgeTX/edgetx
            url: https://github.com/EdgeTX/edgetx/releases/download/v{VERSION}/edgetx-cpn-win64-v{VERSION}.zip
          - id: ente-io.photos-desktop
            repo: ente-io/photos-desktop
            url: https://github.com/ente-io/photos-desktop/releases/download/v{VERSION}/ente-{VERSION}.exe https://github.com/ente-io/photos-desktop/releases/download/v{VERSION}/ente-{VERSION}-x64.exe https://github.com/ente-io/photos-desktop/releases/download/v{VERSION}/ente-{VERSION}-arm64.exe
          - id: f4exb.sdrangel
            repo: f4exb/sdrangel
            url: https://github.com/f4exb/sdrangel/releases/download/v{VERSION}/sdrangel-{VERSION}-win64.exe
          - id: Fabio286.antares
            repo: antares-sql/antares
            url: https://github.com/antares-sql/antares/releases/download/v{VERSION}/Antares-{VERSION}-win_x64.exe
          - id: FilenCloud.Filen-cli
            repo: FilenCloudDienste/filen-cli
            url: https://github.com/FilenCloudDienste/filen-cli/releases/download/v{VERSION}/filen-cli-v{VERSION}-win-x64.exe
          - id: FrancisBanyikwa.MediaDownloader
            repo: mhogomchungu/media-downloader
            url: https://github.com/mhogomchungu/media-downloader/releases/download/{VERSION}/MediaDownloader-{VERSION}.setup.exe
          - id: Gather.Gather
            repo: gathertown/gather-town-desktop-releases
            url: https://github.com/gathertown/gather-town-desktop-releases/releases/download/v{VERSION}/Gather-{VERSION}-Setup.exe
          - id: git-cola.git-cola
            repo: git-cola/git-cola
            url: https://github.com/git-cola/git-cola/releases/download/v{VERSION}/git-cola-{VERSION}.windows.zip
          - id: Gleam.Gleam
            repo: gleam-lang/gleam
            url: https://github.com/gleam-lang/gleam/releases/download/v{VERSION}/gleam-v{VERSION}-x86_64-pc-windows-msvc.zip
          - id: Governikus.AusweisApp
            repo: Governikus/AusweisApp
            url: https://github.com/Governikus/AusweisApp/releases/download/{VERSION}/AusweisApp-{VERSION}.msi
          - id: h3poteto.fedistar
            repo: h3poteto/fedistar
            url: https://github.com/h3poteto/fedistar/releases/download/v{VERSION}/fedistar_{VERSION}_x64_en-US.msi
          - id: Hashicorp.Vault
            repo: hashicorp/vault
            url: https://releases.hashicorp.com/vault/{VERSION}/vault_{VERSION}_windows_amd64.zip https://releases.hashicorp.com/vault/{VERSION}/vault_{VERSION}_windows_386.zip
          - id: henrygd.beszel-agent
            repo: henrygd/beszel
            url: https://github.com/henrygd/beszel/releases/download/v{VERSION}/beszel-agent_windows_amd64.zip https://github.com/henrygd/beszel/releases/download/v{VERSION}/beszel-agent_windows_arm64.zip
          - id: hoppscotch.agent
            repo: hoppscotch/agent-releases
            url: https://github.com/hoppscotch/agent-releases/releases/download/v{VERSION}/Hoppscotch_Agent_win_x64.msi
          - id: hoppscotch.Hoppscotch
            repo: hoppscotch/releases
            url: https://github.com/hoppscotch/releases/releases/download/v{VERSION}/Hoppscotch_win_x64.msi
          - id: JanProchazka.dbgate
            repo: dbgate/dbgate
            url: https://github.com/dbgate/dbgate/releases/download/v{VERSION}/dbgate-{VERSION}-win_arm64.exe https://github.com/dbgate/dbgate/releases/download/v{VERSION}/dbgate-{VERSION}-win_x64.exe https://github.com/dbgate/dbgate/releases/download/v{VERSION}/dbgate-{VERSION}-win.exe
          - id: jdx.mise
            repo: jdx/mise
            url: https://github.com/jdx/mise/releases/download/v{VERSION}/mise-v{VERSION}-windows-x64.zip https://github.com/jdx/mise/releases/download/v{VERSION}/mise-v{VERSION}-windows-arm64.zip
          - id: Jellyfin.FFmpeg
            repo: jellyfin/jellyfin-ffmpeg
            url: https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v{VERSION}/jellyfin-ffmpeg_{VERSION}-portable_win64.zip
          - id: jendrikseipp.RedNotebook
            repo: jendrikseipp/rednotebook
            url: https://github.com/jendrikseipp/rednotebook/releases/download/v{VERSION}/rednotebook-{VERSION}.exe
          - id: JGraph.Draw
            repo: jgraph/drawio-desktop
            url: https://github.com/jgraph/drawio-desktop/releases/download/v{VERSION}/draw.io-ia32-{VERSION}-windows-32bit-installer.exe https://github.com/jgraph/drawio-desktop/releases/download/v{VERSION}/draw.io-{VERSION}-windows-installer.exe https://github.com/jgraph/drawio-desktop/releases/download/v{VERSION}/draw.io-arm64-{VERSION}-windows-arm64-installer.exe https://github.com/jgraph/drawio-desktop/releases/download/v{VERSION}/draw.io-ia32-{VERSION}-windows-32bit-no-installer.exe https://github.com/jgraph/drawio-desktop/releases/download/v{VERSION}/draw.io-{VERSION}-windows-no-installer.exe https://github.com/jgraph/drawio-desktop/releases/download/v{VERSION}/draw.io-arm64-{VERSION}-windows-arm64-no-installer.exe
          - id: JustArchiNET.ArchiSteamFarm
            repo: JustArchiNET/ArchiSteamFarm
            url: https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/{VERSION}/ASF-win-x64.zip
          - id: KeeperSecurity.Commander
            repo: Keeper-Security/Commander
            url: https://github.com/Keeper-Security/Commander/releases/download/v{VERSION}/keeper-commander-windows-v{VERSION}.exe
          - id: Levminer.Authme
            repo: Levminer/authme
            url: https://github.com/Levminer/authme/releases/download/{VERSION}/authme-{VERSION}-windows-x64.msi
          - id: LibreCAD.LibreCAD
            repo: LibreCAD/LibreCAD
            url: https://github.com/LibreCAD/LibreCAD/releases/download/v{VERSION}/LibreCAD-Installer-v{VERSION}.exe
          - id: LibreHardwareMonitor.LibreHardwareMonitor
            repo: LibreHardwareMonitor/LibreHardwareMonitor
            url: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/download/v{VERSION}/LibreHardwareMonitor-net472.zip
          - id: LiveKit.LiveKitCLI
            repo: livekit/livekit-cli
            url: https://github.com/livekit/livekit-cli/releases/download/v{VERSION}/lk_{VERSION}_windows_arm64.zip https://github.com/livekit/livekit-cli/releases/download/v{VERSION}/lk_{VERSION}_windows_amd64.zip https://github.com/livekit/livekit-cli/releases/download/v{VERSION}/lk_{VERSION}_windows_arm.zip
          - id: marha.VcXsrv
            repo: marchaesen/vcxsrv
            url: https://github.com/marchaesen/vcxsrv/releases/download/21.1.16/vcxsrv-64.{VERSION}.0.installer.exe
          - id: Microsoft.Azure.Kubelogin
            repo: Azure/kubelogin
            url: https://github.com/Azure/kubelogin/releases/download/v{VERSION}/kubelogin-win-amd64.zip
          - id: Microsoft.PerfView
            repo: microsoft/perfview
            url: https://github.com/microsoft/perfview/releases/download/v{VERSION}/PerfView.exe
          - id: Microsoft.Sqlcmd
            repo: microsoft/go-sqlcmd
            url: https://github.com/microsoft/go-sqlcmd/releases/download/v{VERSION}/sqlcmd-amd64.msi https://github.com/microsoft/go-sqlcmd/releases/download/v{VERSION}/sqlcmd-arm.msi https://github.com/microsoft/go-sqlcmd/releases/download/v{VERSION}/sqlcmd-arm64.msi
          - id: Min.Min
            repo: minbrowser/min
            url: https://github.com/minbrowser/min/releases/download/v{VERSION}/min-{VERSION}-ia32-setup.exe
          - id: mitmproxy.mitmproxy
            repo: mitmproxy/mitmproxy
            url: https://downloads.mitmproxy.org/{VERSION}/mitmproxy-{VERSION}-windows-x86_64-installer.exe
          - id: Neovim.Neovim
            repo: neovim/neovim
            url: https://github.com/neovim/neovim/releases/download/v{VERSION}/nvim-win64.msi
          - id: openpubkey.opkssh
            repo: openpubkey/opkssh
            url: https://github.com/openpubkey/opkssh/releases/download/v{VERSION}/opkssh-windows-amd64.exe
          - id: OpenTofu.Tofu
            repo: opentofu/opentofu
            url: https://github.com/opentofu/opentofu/releases/download/v{VERSION}/tofu_{VERSION}_windows_386.zip https://github.com/opentofu/opentofu/releases/download/v{VERSION}/tofu_{VERSION}_windows_amd64.zip
          - id: orhun.git-cliff
            repo: orhun/git-cliff
            url: https://github.com/orhun/git-cliff/releases/download/v{VERSION}/git-cliff-{VERSION}-i686-pc-windows-msvc.zip https://github.com/orhun/git-cliff/releases/download/v{VERSION}/git-cliff-{VERSION}-x86_64-pc-windows-gnu.zip https://github.com/orhun/git-cliff/releases/download/v{VERSION}/git-cliff-{VERSION}-aarch64-pc-windows-msvc.zip
          - id: ossia.score
            repo: ossia/score
            url: https://github.com/ossia/score/releases/download/v{VERSION}/ossia.score-{VERSION}-win64.exe
          - id: restic.restic
            repo: restic/restic
            url: https://github.com/restic/restic/releases/download/v{VERSION}/restic_{VERSION}_windows_386.zip https://github.com/restic/restic/releases/download/v{VERSION}/restic_{VERSION}_windows_amd64.zip
          - id: Romanitho.Winget-AutoUpdate
            repo: Romanitho/Winget-AutoUpdate
            url: https://github.com/Romanitho/Winget-AutoUpdate/releases/download/v{VERSION}/WAU.msi
          - id: schollz.croc
            repo: schollz/croc
            url: https://github.com/schollz/croc/releases/download/v{VERSION}/croc_v{VERSION}_Windows-32bit.zip https://github.com/schollz/croc/releases/download/v{VERSION}/croc_v{VERSION}_Windows-64bit.zip https://github.com/schollz/croc/releases/download/v{VERSION}/croc_v{VERSION}_Windows-ARM.zip https://github.com/schollz/croc/releases/download/v{VERSION}/croc_v{VERSION}_Windows-ARM64.zip
          - id: seerge.g-helper
            repo: seerge/g-helper
            url: https://github.com/seerge/g-helper/releases/download/v{VERSION}/GHelper.exe
          - id: shawnbanasick.kade
            repo: shawnbanasick/kade
            url: https://github.com/shawnbanasick/kade/releases/download/v{VERSION}/KADE.Setup.{VERSION}.exe
          - id: Sigstore.Cosign
            repo: sigstore/cosign
            url: https://github.com/sigstore/cosign/releases/download/v{VERSION}/cosign-windows-amd64.exe
          - id: simulot.immich-go
            repo: simulot/immich-go
            url: https://github.com/simulot/immich-go/releases/download/v{VERSION}/immich-go_Windows_arm64.zip https://github.com/simulot/immich-go/releases/download/v{VERSION}/immich-go_Windows_x86_64.zip
          - id: Snyk.Snyk
            repo: snyk/cli
            url: https://github.com/snyk/cli/releases/download/v{VERSION}/snyk-win.exe
          - id: Starpine.Screenbox
            repo: huynhsontung/Screenbox
            url: https://github.com/huynhsontung/Screenbox/releases/download/v{VERSION}/Screenbox_{VERSION}.0_neutral.msixbundle https://github.com/huynhsontung/Screenbox/releases/download/v{VERSION}/Screenbox_{VERSION}.0_neutral.msixbundle https://github.com/huynhsontung/Screenbox/releases/download/v{VERSION}/Screenbox_{VERSION}.0_neutral.msixbundle
          - id: StephanDilly.gitui
            repo: extrawurst/gitui
            url: https://github.com/extrawurst/gitui/releases/download/v{VERSION}/gitui-win.msi
          - id: SurrealDB.SurrealDB
            repo: surrealdb/surrealdb
            url: https://github.com/surrealdb/surrealdb/releases/download/v{VERSION}/surreal-v{VERSION}.windows-amd64.exe https://github.com/surrealdb/surrealdb/releases/download/v{VERSION}/surreal-v{VERSION}.windows-amd64.exe
          - id: SUSE.RancherDesktop
            repo: rancher-sandbox/rancher-desktop
            url: https://github.com/rancher-sandbox/rancher-desktop/releases/download/v{VERSION}/Rancher.Desktop.Setup.{VERSION}.msi
          - id: terreng.SimpleWebServer
            repo: terreng/simple-web-server
            url: https://github.com/terreng/simple-web-server/releases/download/v{VERSION}/Simple-Web-Server-Installer-{VERSION}-x64.exe https://github.com/terreng/simple-web-server/releases/download/v{VERSION}/Simple-Web-Server-Installer-{VERSION}-ia32.exe https://github.com/terreng/simple-web-server/releases/download/v{VERSION}/Simple-Web-Server-Installer-{VERSION}-arm64.exe
          - id: TeXstudio.TeXstudio
            repo: texstudio-org/texstudio
            url:  https://github.com/texstudio-org/texstudio/releases/download/{VERSION}/texstudio-{VERSION}-win-qt6-signed.exe
          - id: ThaUnknown.Miru
            repo: ThaUnknown/miru
            url: https://github.com/ThaUnknown/miru/releases/download/v{VERSION}/win-Miru-{VERSION}-installer.exe
          - id: Typst.Typst
            repo: typst/typst
            url: https://github.com/typst/typst/releases/download/v{VERSION}/typst-x86_64-pc-windows-msvc.zip
          - id: UltimateGadgetLaboratories.UHKAgent
            repo: UltimateHackingKeyboard/agent
            url: https://github.com/UltimateHackingKeyboard/agent/releases/download/v{VERSION}/UHK.Agent-{VERSION}-win-ia32.exe https://github.com/UltimateHackingKeyboard/agent/releases/download/v{VERSION}/UHK.Agent-{VERSION}-win-x64.exe https://github.com/UltimateHackingKeyboard/agent/releases/download/v{VERSION}/UHK.Agent-{VERSION}-win.exe
          - id: VictorIX.BlenderLauncher
            repo: Victor-IX/Blender-Launcher-V2
            url: https://github.com/Victor-IX/Blender-Launcher-V2/releases/download/v{VERSION}/Blender_Launcher_v{VERSION}_Windows_x64.zip
          - id: WerWolv.ImHex
            repo: WerWolv/ImHex
            url: https://github.com/WerWolv/ImHex/releases/download/v{VERSION}/imhex-{VERSION}-Windows-x86_64.msi
          - id: WidelandsDevelopmentTeam.Widelands
            repo: widelands/widelands
            url: https://github.com/widelands/widelands/releases/download/v{VERSION}/Widelands-{VERSION}-x64.exe https://github.com/widelands/widelands/releases/download/v{VERSION}/Widelands-{VERSION}-x86.exe
          - id: woaitsAryan.regit
            repo: woaitsAryan/regit
            url: https://github.com/woaitsAryan/regit/releases/download/v{VERSION}/regit_Windows_arm64.zip https://github.com/woaitsAryan/regit/releases/download/v{VERSION}/regit_Windows_x86_64.zip
          - id: Yubico.Authenticator
            repo: Yubico/yubioath-flutter
            url: https://github.com/Yubico/yubioath-flutter/releases/download/{VERSION}/yubico-authenticator-{VERSION}-win64.msi
          - id: Yubico.YubiKeyManagerCLI
            repo: Yubico/yubikey-manager
            url: https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-{VERSION}-win64.msi
          - id: ZugferdCommunity.QubaViewer
            repo: ZUGFeRD/quba-viewer
            url: https://github.com/ZUGFeRD/quba-viewer/releases/download/v{VERSION}/Quba.{VERSION}.msi

    steps:
    - name: Update Packages
      uses: b0t-at/winget-updater@b0t-main
      with:
        identifier: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}
        komac-token: ${{ secrets.WINGET_PAT }}
        komac-version: 2.10.1
        custom-fork-owner: damn-good-b0t
        submit: ${{ vars.SUBMIT_PR }}
        pre-release: ${{ matrix.pre-release }}
