name: Update via Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: 7 0/4 * * *

jobs:
  update-scriptbased:
    name: ${{ matrix.PackageName }}
    runs-on: windows-latest
    
    strategy:
      matrix:
        include:
          - PackageName: "MongoDB.Server"
            WebsiteURL: "https://www.mongodb.com/try/download/community"          
          - PackageName: "MongoDB.MongoDBCLI"
            WebsiteURL: "https://www.mongodb.com/try/download/tools"
          - PackageName: "MongoDB.Shell"
            WebsiteURL: "https://www.mongodb.com/try/download/tools"          
          - PackageName: "MongoDB.MongoDBAtlasCLI"
            WebsiteURL: "https://www.mongodb.com/try/download/tools"
          - PackageName: "MongoDB.DatabaseTools"
            WebsiteURL: "https://www.mongodb.com/try/download/tools"          
          - PackageName: "MongoDB.Compass"
            WebsiteURL: "https://www.mongodb.com/try/download/tools"
          - PackageName: "Logitech.OptionsPlus"
            WebsiteURL: "https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.exe"          
          - PackageName: "Glarysoft.GlaryUtilities"
            WebsiteURL: "https://download.glarysoft.com/gusetup.exe"
          - PackageName: "Gitbutler.GitButler"
            WebsiteURL: "https://app.gitbutler.com/downloads/release/windows/x86_64/msi"          
          - PackageName: "FlipperDevicesInc.qFlipper"
            WebsiteURL: "https://update.flipperzero.one/qFlipper/directory.json"
          - PackageName: "Loupedeck.Loupedeck"
            WebsiteURL: "https://download.loupedeck.com/software/latest-win"
          - PackageName: "StrawberryPerl/StrawberryPerl"
            WebsiteURL: "https://github.com/StrawberryPerl/Perl-Dist-Strawberry"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Install winget
#        uses: Cyberboss/install-winget@v1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update package
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
          WINGET_PKGS_FORK_REPO: ${{ vars.WINGET_PKGS_FORK_REPO }}
          WebsiteURL: ${{ matrix.WebsiteURL }}
          PackageName: ${{ matrix.PackageName }}
        run: .\Scripts\Update-${{ matrix.PackageName }}.ps1


